### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by justin604** [lxyu/kindle-clippings#20]
```
Traceback (most recent call last):
  File "kindle.py", line 94, in <module>
    main()
  File "kindle.py", line 89, in main
    save_clips(clips)
  File "kindle.py", line 70, in save_clips
    json.dump(clips, f)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 180, in dump
    fp.write(chunk)
TypeError: a bytes-like object is required, not 'str'
```

**Comment by Chanuttha** [comment]
MilkShakeYoung updated it for Python3
https://github.com/lxyu/kindle-clippings/pull/14#issue-161416641
