### ISSUE TITLE
【求助】运行错误。

### ISSUE THREAD

**Issue by cyang812** [lxyu/kindle-clippings#6]
错误代码如下：
Traceback (most recent call last):
  File "kindle.py", line 94, in <module>
    main()
  File "kindle.py", line 90, in main
    export_txt(clips)
  File "kindle.py", line 50, in export_txt
    with open(filename, 'w') as f:
IOError: [Errno 2] No such file or directory: u'output/Who Moved My Cheese? (Spencer Johnson).md'

**Comment by cyang812** [comment]
再次尝试，出现以下错误：
Traceback (most recent call last):
  File "F:/Pycharm_projects/kindle/kindle.py", line 94, in <module>
    main()
  File "F:/Pycharm_projects/kindle/kindle.py", line 86, in main
    clips = {k: v for k, v in clips.iteritems() if v}
AttributeError: 'collections.defaultdict' object has no attribute 'iteritems'
